version: '3'

services:
#---------------------------
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ajhsdWEd
      MYSQL_DATABASE: dfdx
      MYSQL_USER: docker_test_alex
      MYSQL_PASSWORD: 1111
    volumes:
      - mysql_bd_ipcalculator:/var/lib/mysql
    networks:
      - networkName1
#---------------------------
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ajhsdWEd
    networks:
      - networkName1
#---------------------------

  calculator:
    image: alexmway78224/ip_calculator
    ports: 
      - "98:90"
    command: php -S 0.0.0.0:90
    volumes:
      - ipcalculator_php:/app
      - /c/xampp/htdocs/IPCalculator:/app
    networks:
      - networkName1

volumes:
  mysql_bd_ipcalculator:
  ipcalculator_php:

networks:
  networkName1:
