version: '3'

services:
#---------------------------
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ajhsdWEd
      MYSQL_DATABASE: dfdx
      MYSQL_USER: docker_test_alex
      MYSQL_PASSWORD: 1111
    # volumes:
    #   - mysql_bd_ipcalculator:/var/lib/mysql

#---------------------------
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ajhsdWEd
#---------------------------

  calculator:
    build: 
      context: .
    ports: 
      - "98:90"
    command: php -S 0.0.0.0:90
    volumes:
      - ipcalculator_php:/app

volumes:
  mysql_bd_ipcalculator:
  ipcalculator_php:


